services:
  nginx:
    build:
      context: .docker/nginx/
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html/:ro,cached
      - ./.var/log/:/var/www/html/.var/log/:cached
    networks:
      - app
    depends_on:
      - app

  app:
    container_name: app
    build:
      context: .
      dockerfile: .docker/php-fpm/Dockerfile
    volumes:
      - ./:/var/www/html/:cached
    networks:
      - app
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:9.1
    platform: linux/x86_64
    environment:
      #MYSQL_USER: ${DB_USER}
      #MYSQL_PASSWORD: ${DB_PWD} # TODO: use secrets instead
      MYSQL_ROOT_PASSWORD: ${DB_PWD} # Just for local development
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - ./.var/db-data:/var/lib/mysql:delegated
    healthcheck:
      test: ["CMD-SHELL", 'mysql --database=$$MYSQL_DATABASE --password=$$MYSQL_ROOT_PASSWORD --execute="SELECT 1 FROM information_schema.tables;" --skip-column-names -B']
      interval: 2s
      timeout: 10s
      retries: 20
    networks:
      - app

networks:
  app:
    name: app
